# TNO Terminology Design tools configuration file (yaml)

## General
scopedir: __tests__/content # path of the scope directory where the SAF is located
onNotExist: warn # the action in case a `vsntag` was specified, but wasn't found in the SAF
output: __tests__/output # (root) directory for output files to be written

## Machine Readable Glossary Tool
mrgt:
  vsntag: # versiontag for which the MRG needs to be (re)generated. Leave empty to process all versions
  macros: # macros to be used for formPhrases
    "{ss}": ["", "s", "'s", "(s)"]
    "{ess}": ["", "es", "'s", "(es)"]
    "{yies}": ["y", "y's", "ies"]
    "{ying}": ["y", "ying", "ies", "ied"]
    "{es}": ["e", "es", "ed", "ing"]
    "{able}": ["able", "ability"]

## Human Readable Glossary Tool
hrgt:
  interpreter: default
  converter: |
    ### [{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}]({{localize navurl}})\n
    {{#if glossaryText}}{{glossaryText}}{{else}}no `glossaryText` was specified for this entry.{{/if}}\n
  force: true
  input:
    - "__tests__/content/**/mockup*"

## Term Reference Resolution Tool
trrt:
  interpreter: default
  converter: >- # Type of converter, either: a mustache template, "http", or "markdown"
    <a
    href="{{localize navurl}}{{#if ref.trait}}#{{ref.trait}}{{/if}}"
    hovertext="{{#if hoverText}}{{hoverText}}{{else}}{{#if glossaryTerm}}{{glossaryTerm}}{{else}}{{capFirst term}}{{/if}}: {{noRefs glossaryText type="markdown"}}{{/if}}"
    >{{ref.showtext}} ({{err.line}}, {{err.pos}})</a>
  converter[7]: This converter is used on and after the 7th occurrence of a term reference, in this case '{{term}}:{{termType}}'
  force: true # toggle overwriting of existing files
  input: # glob pattern strings for files to be processed by the TRRT
    - "__tests__/output/**/mockup*"
  output: .
